#!/usr/bin/env python
"""Structural-integrity manifest for the committed ``tests/fixtures`` evidence base.

The §4 verdicts (the SHIP recommendation) rest on a small set of committed JSON
/ JSONL fixtures under ``tests/fixtures/`` — the candidate-vs-surrogate deposits,
their ledgers / run-logs, and the negative-control / proxy deposits. Those bytes
ARE the citable evidence. :mod:`src.tg_lora.freeze_evidence_hash` already pins an
IN-BAND semantic hash over the measurement keys inside a single deposit (what the
verdict is computed from). This module is the complementary OUT-OF-BAND layer:

  * **scope**: per-file ``path`` + ``sha256`` (whole-file raw bytes) + ``size`` —
    the structural triple, deliberately NOT the content/semantic axes (the
    in-band hash owns those; hashing them again here would be circular). The
    instruction's "structural-integrity scope: path/sha256/size, NOT content
    axes" forbids re-deriving content here.
  * **coverage**: every committed fixture, recursively (``advise_loop/`` subdir
    included), not just the deposit a given verdict cites.
  * **what it catches**: whole-file tampering (a flipped byte changes the
    sha256), a fixture deleted but left referenced, and a fixture added but not
    registered — drift at the filesystem boundary that the in-band producer
    cannot see (the producer hashes only its own output's measurement keys).

The manifest is regenerated by this script and verified by
``tests/test_artifact_manifest_integrity.py`` — a pure-local check (no AI-Hub
co-location, no GPU, no network) that therefore runs in CI / a plain checkout,
not only in the make-run workspace.

Usage::

    # verify the committed manifest against the live tree (default; non-mutating)
    python scripts/generate_artifact_manifest.py
    python scripts/generate_artifact_manifest.py --check   # explicit

    # regenerate + atomically write the manifest (only when fixtures legitimately change)
    python scripts/generate_artifact_manifest.py --write
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any, Iterator

# Standalone-CLI bootstrap: a bare ``python scripts/...`` invocation puts
# ``scripts/`` (not the repo root) on sys.path, so make the repo root importable
# so ``src.*`` resolves without a PYTHONPATH wrapper (matches the idiom in
# ``generate_advise_loop_fixture.py`` / ``benchmark_prefix_cache.py``).
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.utils.io import load_json, save_json  # noqa: E402

MANIFEST_FILENAME = "artifact_manifest.json"
SCHEMA_VERSION = 1

_REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASE_DIR = _REPO_ROOT / "tests" / "fixtures"


def _repo_relative(base_dir: Path) -> str:
    """The ``base_dir`` value stamped into the manifest (informational).

    Stored repo-relative for portability across worktrees / machines; falls back
    to the absolute string when ``base_dir`` is outside the repo (e.g. a temp
    dir under pytest's ``tmp_path``). Correctness never depends on this string —
    :func:`verify_manifest` re-walks the actual ``base_dir`` path passed in.
    """
    try:
        return str(base_dir.relative_to(_REPO_ROOT)).replace("\\", "/")
    except ValueError:
        return str(base_dir)


def iter_artifact_files(base_dir: Path) -> Iterator[str]:
    """Yield every fixture file under *base_dir*, POSIX-relative & sorted.

    The manifest file itself is excluded (self-reference would be circular: its
    own bytes change whenever any entry changes, so no fixed sha256 exists).
    """
    manifest_names = {MANIFEST_FILENAME}
    rel_paths: list[str] = []
    for path in base_dir.rglob("*"):
        if not path.is_file():
            continue
        if path.name in manifest_names:
            continue
        rel = path.relative_to(base_dir).as_posix()
        rel_paths.append(rel)
    yield from sorted(rel_paths)


def hash_file(path: Path) -> tuple[str, int]:
    """Return ``(sha256 hexdigest, size in bytes)`` for *path*'s raw bytes."""
    data = path.read_bytes()
    return hashlib.sha256(data).hexdigest(), len(data)


def build_manifest(base_dir: Path) -> dict[str, Any]:
    """Build the manifest dict for every fixture under *base_dir*.

    Deterministic by construction: artifacts are sorted by relative path and
    each entry's keys are emitted in fixed insertion order, so re-running the
    producer yields byte-identical output (pinned by the verifier test's
    canonical-serialization assertion).
    """
    artifacts: list[dict[str, Any]] = []
    for rel in iter_artifact_files(base_dir):
        sha256, size = hash_file(base_dir / rel)
        artifacts.append({"path": rel, "sha256": sha256, "size": size})
    return {
        "schema_version": SCHEMA_VERSION,
        "base_dir": _repo_relative(base_dir),
        "artifact_count": len(artifacts),
        "scope": "structural-integrity: path / sha256 / size (NOT content axes)",
        "artifacts": artifacts,
    }


def manifest_path(base_dir: Path) -> Path:
    return base_dir / MANIFEST_FILENAME


def write_manifest(base_dir: Path) -> Path:
    """Regenerate the manifest and atomically publish it under *base_dir*.

    Routes through :func:`src.utils.io.save_json` — the sole atomic JSON publish
    point — so a mid-write fault can never leave a half-written manifest.
    """
    manifest = build_manifest(base_dir)
    out = manifest_path(base_dir)
    save_json(manifest, out)
    return out


def verify_manifest(base_dir: Path) -> tuple[bool, list[str]]:
    """Recompute the live manifest and diff it against the committed one.

    Returns ``(ok, diffs)``. ``diffs`` is human-readable, one line per
    discrepancy; empty iff the committed manifest exactly matches the live tree.
    """
    out = manifest_path(base_dir)
    if not out.is_file():
        return False, [f"manifest missing: {out} (run with --write to create)"]
    committed = load_json(out)
    live = build_manifest(base_dir)

    diffs: list[str] = []

    committed_by_path = {a["path"]: a for a in committed.get("artifacts", [])}
    live_by_path = {a["path"]: a for a in live["artifacts"]}

    for path, live_entry in live_by_path.items():
        if path not in committed_by_path:
            diffs.append(
                f"untracked artifact present in tree but absent from manifest: "
                f"{path} (sha256={live_entry['sha256']}, size={live_entry['size']})"
            )
            continue
        committed_entry = committed_by_path[path]
        if committed_entry.get("sha256") != live_entry["sha256"]:
            diffs.append(
                f"sha256 mismatch for {path}: manifest="
                f"{committed_entry.get('sha256')} live={live_entry['sha256']}"
            )
        if committed_entry.get("size") != live_entry["size"]:
            diffs.append(
                f"size mismatch for {path}: manifest="
                f"{committed_entry.get('size')} live={live_entry['size']}"
            )

    for path in committed_by_path:
        if path not in live_by_path:
            diffs.append(
                f"stale manifest entry: {path} listed but file is missing from tree"
            )

    if committed.get("artifact_count") != live["artifact_count"]:
        diffs.append(
            f"artifact_count mismatch: manifest="
            f"{committed.get('artifact_count')} live={live['artifact_count']}"
        )

    if committed.get("schema_version") != SCHEMA_VERSION:
        diffs.append(
            f"schema_version drift: manifest="
            f"{committed.get('schema_version')} producer={SCHEMA_VERSION}"
        )

    return (len(diffs) == 0), diffs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=DEFAULT_BASE_DIR,
        help=f"fixtures dir to manifest (default: {DEFAULT_BASE_DIR}).",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--write",
        action="store_true",
        help="regenerate and atomically write the manifest (default: verify only).",
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="verify the committed manifest against the live tree (default).",
    )
    args = parser.parse_args(argv)

    base_dir: Path = args.base_dir
    if not base_dir.is_dir():
        print(f"error: base dir does not exist: {base_dir}", file=sys.stderr)
        return 2

    if args.write:
        out = write_manifest(base_dir)
        manifest = load_json(out)
        print(
            f"wrote {out} — {manifest['artifact_count']} artifact(s) "
            f"under {manifest['base_dir']}"
        )
        return 0

    ok, diffs = verify_manifest(base_dir)
    if ok:
        manifest = load_json(manifest_path(base_dir))
        print(
            f"OK — {manifest['artifact_count']} artifact(s) match the committed manifest."
        )
        return 0
    print(
        "MANIFEST DRIFT — live fixtures do not match committed manifest:",
        file=sys.stderr,
    )
    for line in diffs:
        print(f"  - {line}", file=sys.stderr)
    print(
        "  (run `python scripts/generate_artifact_manifest.py --write` to regenerate)",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
